import React from 'react';
import { ShieldAlert, AlertTriangle } from 'lucide-react';

interface ForensicDisclaimerProps {
  compact?: boolean;
}

export const ForensicDisclaimer: React.FC<ForensicDisclaimerProps> = ({ compact = false }) => {
  if (compact) {
    return (
      <div className="flex items-center gap-2 bg-amber-500/10 border border-amber-500/30 px-3 py-1.5 rounded text-xs text-amber-300">
        <AlertTriangle className="w-3.5 h-3.5 flex-shrink-0 text-amber-400" />
        <span>
          <strong>ALGORITHMIC PREDICTION:</strong> Secondary human verification required. Not definitive proof of identity.
        </span>
      </div>
    );
  }

  return (
    <div className="bg-navy-900/80 border border-amber-500/30 rounded-lg p-3.5 shadow-sm text-xs text-slate-300 flex items-start gap-3">
      <div className="p-2 rounded bg-amber-500/10 border border-amber-500/20 text-amber-400 flex-shrink-0 mt-0.5">
        <ShieldAlert className="w-4 h-4" />
      </div>
      <div className="space-y-1">
        <div className="flex items-center gap-2">
          <span className="font-semibold text-amber-400 tracking-wider uppercase text-[11px]">
            Forensic & Biometric Ethics Advisory (NIST FRTE / SWGDE Standards)
          </span>
          <span className="bg-cyan-500/20 text-cyan-300 border border-cyan-500/30 text-[10px] px-1.5 py-0.2 rounded font-mono">
            RESEARCH PROTOTYPE
          </span>
        </div>
        <p className="text-slate-400 leading-relaxed text-[11.5px]">
          All facial sketch syntheses, DeepSORT tracks, and ArcFace/FaceNet embeddings generated by this platform are
          probabilistic investigative leads. In accordance with forensic science guidelines, biometric matching scores
          <strong> DO NOT constitute definitive legal proof of identity</strong> and must be peer-reviewed by a certified
          Forensic Facial Comparison (FFC) examiner prior to evidentiary submission.
        </p>
      </div>
    </div>
  );
};
